spring:
  application:
    name: url_service

  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    password: mypassword
    username: urlshortener
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

app:
  base-url: "http://localhost:8080"
  node-id: 01

logging:
  level:
    sh.kamath.url_service: DEBUG
